# Generated by Django 4.2.6 on 2023-10-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todoApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="name",
            new_name="todo_name",
        ),
    ]
